---
title: "Cars-data"
author: "Yaswanth Pulavarthi"
date: "9/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading data


```{r cars}
library(datasets)
data(mtcars)
head(mtcars)
library(ggplot2)
```

## Processing Data



```{r dataProccess }
mtcars$cyl <- as.factor(mtcars$cyl)
mtcars$vs <- as.factor(mtcars$vs)
mtcars$am <- as.factor(mtcars$am)
mtcars$gear <- factor(mtcars$gear)
mtcars$carb<- factor(mtcars$carb)
str(mtcars)

```


## Basic Exploratory analysis



```{r }
boxplot(mpg~am, mtcars)
```



```{r }

aggregate(mpg ~ am, data = mtcars, mean)

```
## single var fit



```{r }
FitAM <- lm(mpg ~ am, data = mtcars)
summary(FitAM)

```




## multi variable fit



```{r multifit }
multiVarFit <- lm(mpg ~., data = mtcars)
summary(multiVarFit)
```

```{r }
anova(FitAM,multiVarFit)
```
here using multivarfit we can reject the null hypothesis but their is significant change from fitam

```{r}
t.test(mtcars$mpg~mtcars$am)

```

P-value less than 0.05 concludes that manual transmission works better than automatic.


## best fit

```{r bestfit}





```